### ISSUE TITLE
This works, but is it possible to install 2.0 and Nitrox at the same time?

### ISSUE THREAD

**Issue by ghost** [xdrm-io/nitrux#1]
Following the script from scratch works well (by adding %command% to the start of the Launch Command), and I can launch both a server and a client in multiplayer mode when the game is patched correctly. However, I'd like to have vanillia Subnautica and Nitrox installed at the same time.

I have tried:

1. Install Nitrox/patch the game using the script as usual
2. Copy ~/.local/share/Steam/steamapps/compatdata/264710 to ~/game/Nitrox/compatdata and ~/.local/share/Steam/steamapps/common/Subnautica to ~/game/Nitrox/Subnautica
3. Add the game to Steam by adding ~/game/Nitrox/Subnautica/Subnautica.exe
4. Run Steam in a terminal to show the internal Game ID when starting the 'non-Steam' game
5. ln -s ~/game/Nitrox/compatdata ~/.local/share/Steam/steamapps/compatdata/$GAME_ID
6. Set launch command of added game to `%command% -nitrox C:\Nitrox\`

When I have the launch command, the Steam console says `bash: -nitrox: command not found` when the game is started, but launches the real Subnautica (even 2.0 when that's installed) when there isn't a command. See the attached log that shows this behaviour: 

[2024-02-11.log](https://github.com/user-attachments/files/18748180/2024-02-11.log)

To me, this should produce an identical environment, just in a different location. What could I be missing here?

**Comment by xdrm-io** [comment]
Can you clarify what you want precisely ?

> I'd like to have vanillia Subnautica and Nitrox installed at the same time.
Subnautica is the game you have on steam. Nitrox is the launcher to run the server or to patch the game and launch it in one go. Technically, you already have (and must have) both at the same time.

Depending on your need, the solution differs, here are my takes on a few.

### 1) You want to switch from Subnautica (vanilla) and Subnautica (Nitrox)

For the vanilla game :
- remove the launch command
For the Nitrox game (multiplayer) :
- set the launch command `-nitrox C:\Nitrox\`

I you find a way to automate it, it would make it even easier.

### 2) You want to play Subnautica (vanilla) and run a Nitrox server at the same time

Personnally I use this docker compose to keep my server running for my friends. 

```yaml
---
services:
  nitrox:
    image: docker.io/fuzzystatic/nitrox-server:latest
    container_name: nitrox-server
    volumes:
      - /path-to-config:/config
      - /path-to-subnautica-copy:/subnautica
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Your/Timezone
      - SUBNAUTICA_INSTALLATION_PATH=/subnautica
    ports:
      - "1234:11000/udp"
    restart: "unless-stopped"
```

With :
- `TZ` : your timezonbe
- `1234` : the port you want to open for your friends
- `/path-to-config` : path where you want nitrox server to store config and world data
- `/path-to-subnautica-copy` : path to a copy of `$STEAM_DIR/steamapps/common/Subnautica`

Launch with : `docker compose pull && docker compose up -d`
Stop with : `docker compose down`

You can backup the folder `/path-to-config/world` which contains the state of your server.

To switch to the native game : refer to case **1)**

### You want to play Subnautica (vanilla) and Subnautica (multiplayer) at the same time

> [!warning]
> The script might not be working if the Nitrox game is not the default steam game but the one you copied.

But anyway, your approach seems reasonable. I cannot help you further on this topic, it heavily relies on how steam manages games, and how Subnautica and Nitrox have been developed.
When I tried launching the Nitrox non-steam game, it stopped right away and started launching the original game instead.
